<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - TCPConnectionTest</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>TCPConnectionTest</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/org.york.network.TCP.connection.html">org.york.network.TCP.connection</a> &gt; TCPConnectionTest</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">5</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">5</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">0.168s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">0%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div class="tab-container">
<ul class="tabLinks">
<li>
<a href="#">Failed tests</a>
</li>
<li>
<a href="#">Tests</a>
</li>
<li>
<a href="#">Standard error</a>
</li>
</ul>
<div class="tab">
<h2>Failed tests</h2>
<div class="test">
<a name="testClientCreation()"></a>
<h3 class="failures">testClientCreation()</h3>
<span class="code">
<pre>java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:108)
	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1425)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:328)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:387)
	at org.york.network.TCP.connection.TCPConnection.&lt;init&gt;(TCPConnection.java:22)
	at org.york.network.TCP.connection.TCPServerConnection.&lt;init&gt;(TCPServerConnection.java:18)
	at org.york.network.TCP.connection.TCPConnectionTest.setUp(TCPConnectionTest.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</span>
</div>
<div class="test">
<a name="testConnectionClose()"></a>
<h3 class="failures">testConnectionClose()</h3>
<span class="code">
<pre>java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:108)
	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1425)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:328)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:387)
	at org.york.network.TCP.connection.TCPConnection.&lt;init&gt;(TCPConnection.java:22)
	at org.york.network.TCP.connection.TCPServerConnection.&lt;init&gt;(TCPServerConnection.java:18)
	at org.york.network.TCP.connection.TCPConnectionTest.setUp(TCPConnectionTest.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</span>
</div>
<div class="test">
<a name="testDataTransmission()"></a>
<h3 class="failures">testDataTransmission()</h3>
<span class="code">
<pre>org.opentest4j.AssertionFailedError: expected: not &lt;null&gt;
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:152)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertNotNull.failNull(AssertNotNull.java:49)
	at app//org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:35)
	at app//org.junit.jupiter.api.AssertNotNull.assertNotNull(AssertNotNull.java:30)
	at app//org.junit.jupiter.api.Assertions.assertNotNull(Assertions.java:304)
	at app//org.york.network.TCP.connection.TCPConnectionTest.testDataTransmission(TCPConnectionTest.java:115)
	at java.base@21.0.7/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base@21.0.7/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21.0.7/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</span>
</div>
<div class="test">
<a name="testServerCreation()"></a>
<h3 class="failures">testServerCreation()</h3>
<span class="code">
<pre>java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:108)
	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1425)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:328)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:387)
	at org.york.network.TCP.connection.TCPConnection.&lt;init&gt;(TCPConnection.java:22)
	at org.york.network.TCP.connection.TCPServerConnection.&lt;init&gt;(TCPServerConnection.java:18)
	at org.york.network.TCP.connection.TCPConnectionTest.setUp(TCPConnectionTest.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</span>
</div>
<div class="test">
<a name="testThreeWayHandshake()"></a>
<h3 class="failures">testThreeWayHandshake()</h3>
<span class="code">
<pre>java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1329)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1299)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.bind(DatagramSocketAdaptor.java:108)
	at java.base/java.net.DatagramSocket.createDelegate(DatagramSocket.java:1425)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:328)
	at java.base/java.net.DatagramSocket.&lt;init&gt;(DatagramSocket.java:387)
	at org.york.network.TCP.connection.TCPConnection.&lt;init&gt;(TCPConnection.java:22)
	at org.york.network.TCP.connection.TCPServerConnection.&lt;init&gt;(TCPServerConnection.java:18)
	at org.york.network.TCP.connection.TCPConnectionTest.setUp(TCPConnectionTest.java:19)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
</pre>
</span>
</div>
</div>
<div class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="failures">testClientCreation()</td>
<td class="failures">0.002s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">testConnectionClose()</td>
<td class="failures">0.002s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">testDataTransmission()</td>
<td class="failures">0.157s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">testServerCreation()</td>
<td class="failures">0.002s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">testThreeWayHandshake()</td>
<td class="failures">0.005s</td>
<td class="failures">failed</td>
</tr>
</table>
</div>
<div class="tab">
<h2>Standard error</h2>
<span class="code">
<pre>Exception in thread &quot;Thread-3&quot; org.opentest4j.AssertionFailedError: Server error: Error de secuencias de paquete esperadas
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:38)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:138)
	at org.york.network.TCP.connection.TCPConnectionTest.lambda$testDataTransmission$2(TCPConnectionTest.java:94)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</span>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="https://www.gradle.org">Gradle 9.0.0</a> at Sep 13, 2025, 10:09:36â€¯PM</p>
</div>
</div>
</body>
</html>
